upstream cardapio_backend {
    server cardapio:8000;
    keepalive 32;
}

server {
    listen 443 ssl http2;
    server_name nachapa.2ulabs.com.br;

    ssl_certificate     /etc/nginx/ssl/nachapa.crt;
    ssl_certificate_key /etc/nginx/ssl/nachapa.key;

    include /etc/nginx/snippets/ssl-params.conf;

    client_max_body_size 100m;

    location / {
        proxy_pass         http://cardapio_backend;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;
    }
}

server {
    listen 80;
    server_name nachapa.2ulabs.com.br;
    return 301 https://$host$request_uri;
}
